### ISSUE TITLE
Chatgpt / o1 support

### ISSUE THREAD

**Issue by hashcacher** [pasky/claude.vim#13]
I've been enjoying this plugin recently. With o1-preview out, I'd there any plan to integrate it?

**Comment by pasky** [comment]
Thanks! This plugin is named Claude and also there's value in simplicity, so I don't want to add complexity by supporting multiple backends, in particular since Claude still remains consistently the top coding assistant in the eyes of many (in particular with Sonnet 3.6v2, but some would argue that even before).

One way to introduce alternative backends would be to use the same adapter mechanism as we use for AWS bedrock, though. I'd be happy for MRs in that direction.

**Comment by hashcacher** [comment]
Agreed that Claude is still the top one, so there's no need for this feature yet. For a second, I thought o1 was going to outperform Claude, but that didn't turn out.
